apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pod
  namespace: mynamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-readonly
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: devopsread
