apiVersion: v1
kind: Pod
metadata:
  name: activity-pod
  namespace: mynamespace
spec:
  containers:
    - name: ubuntu-1
      image: ubuntu
      command: ['/bin/bash','-ec','echo "Data written by container 1" > /data/application/data.txt; sleep 3600']
      volumeMounts:
        - mountPath: /data/application
          name: pvc-claim
    - name: ubuntu-2
      image: ubuntu
      command: ['/bin/bash', '-ec', 'cat /data/application/data.txt; sleep 3600']
      volumeMounts:
        - mountPath: /data/application
          name: pvc-claim
  volumes:
    - name: pvc-claim
      persistentVolumeClaim:
        claimName: activity-local-claim    
