apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c2labs-files
  namespace: mynamespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 1Gi
