apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: mynamespace
  labels:
    app: batch-job
    environment: dev
    jobgroup: investment-job
spec:
  template:
    metadata:
      labels:
        jobgroup: investment-job
    spec:
      containers:
        - image: devopscube/kubernetes-job-demo:latest
          name: job1
          args: ["100"]
      restartPolicy: OnFailure       
