apiVersion: v1
kind: Service
metadata:
  name: nginx-service 
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  clusterIP: 10.96.0.5    
  selector:
    app: nginx
    environment: production    
