apiVersion: v1
kind: Service
metadata:
  name: nginx-service 
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.5
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: nginx
    environment: production    
