apiVersion: v1
kind: Pod
metadata:
  name: aws-pod-ex
spec:
  containers:
    - name: testpod
      image: alpine:latest
      volumeMounts:
        - mountPath: /test/files
          name: test-files
  volumes:
    - name: test-files
      persistentVolumeClaim:
        claimName: c2labs-files
