apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: mynamespace
spec:
  containers:
    - name: container1
      image: nginx
      command:
        - /bin/bash
        - -ec
        - while :; do echo "."; sleep 5; done       
