apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: mynamespace
spec:
  containers:
    - name: container1
      image: nginx
      resources:
        limits:
          memory: "128G"
          cpu: "1000"
        requests:
          memory: "64G"
          cpu: "500"      
