apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: mynamespace
spec:
  containers:
    - name: container1
      image: ubuntu
      command:
        - /bin/bash
        - -ec
        - touch /tmp/live; sleep 30; rm /tmp/live ; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/live
        initialDelaySeconds: 5
        periodSeconds: 5     
