apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      name: nginx-app
      labels:
        environment: production
    spec:
      containers:
        - name: container-nginx
          image: nginx     
