apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-empty-dir
spec:
  containers:
    - name: container1 
      image: nginx
      volumeMounts:
        - mountPath: /mounted-data
          name: data-volume
  volumes:
    - name: data-volume
      emptyDir: {}      
