apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-empty-dir
spec:
  containers:
    - name: container1 
      image: ubuntu
      command: ['/bin/bash', '-ec', 'sleep 3600']
      volumeMounts:
        - mountPath: /mounted-data
          name: data-volume
    - name: container2
      image: ubuntu
      command: ['/bin/bash', '-ec', 'sleep 3600' ]
      volumeMounts:
        - mountPath: /mounted-data
          name: data-volume       
          
  volumes:
    - name: data-volume
      emptyDir: {}      
