apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activity-local-claim
  namespace: mynamespace
spec:
  storageClassName: activity-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: activity-pod
  namespace: mynamespace
spec:
  containers:
    - name: ubuntu-1
      image: ubuntu
      command: ['/bin/bash','-ec','echo "Data written by container-1" >  /data/application/data.txt; sleep 3600']
      volumeMounts:
        - mountPath: /data/application
          name: pvc-volume
    - name: ubuntu-2
      image: ubuntu
      command: ['/bin/bash','-ec','sleep 30; cat /data/application/data.txt; sleep 3600']
      volumeMounts:
        - mountPath: /data/application
          name: pvc-volume
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: activity-local-claim
