apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-ex
spec:
  selector:
    matchLabels:
      app: postgre-ex
  template:
    metadata:
      labels:
        app: postgre-ex
    spec:
      containers:
        - name: db
          image: postgres:11.6-alpine
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /db-secrets/password
          volumeMounts:
            - name: secret
              mountPath: "/db-secrets"
      volumes:
        - name: secret
          secret:
            secretName: postgres-secret
            defaultMode: 0400
            items:
              - key: PASSWORD
                path: password
