apiVersion: v1
kind: Service
metadata:
  name: postgres-ex
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-ex
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ex
spec:
  selector:
    matchLabels:
      app: postgres-ex
  template:
    metadata:
      labels:
        app: postgres-ex
    containers:
      - name: db
        image: postgres:11.6-alpine
         env:
           - name: POSTGRES_PASSWORD_FILE
             value: /db-secrets/password
          volumeMounts:
            - name: secret
              mountPath: "/db-secrets"
    volumes:
      - name: secret
        secret:
          secretName: postgres-secret
          defaultMode: 0400
          items:
            - key: PASSWORD
              path: password    
