apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-ec", "env; sleep 3600;"]
      env:
        - name: EXAMPLE_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: key1
        - name: EXAMPLE_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: key2      

      envFrom:
        - configMapRef:
            name: env-config
