apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
    # namespace omitted since ClusterRoles are not namespaced 
  name: Pod-reader 
rules:
  - apiGroups: [""]
    resources: [""] # object is secrets 
    verbs: ["get", "watch", "list"]
