apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-Pods
  namespace: mynamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: arunstiwari
