apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mynamespace
  name: pod-reader
rules:
  - apiGroups: ["","apps"]
    resources: ["pods","deployments"]
    verbs: ["get", "watch", "list"]

