apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: k8s.gcr.io/busybox
      command: [ '/bin/sh', '-ec', 'env' ]
      envFrom:
        - configMapRef:
            name: configmap1
